"""rich_move_analysis

Revision ID: 160707205ff6
Revises: 62da53931d77
Create Date: 2026-04-14 21:14:31.721588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '160707205ff6'
down_revision: Union[str, Sequence[str], None] = '62da53931d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_summaries', sa.Column('accuracy_white', sa.Float(), nullable=True))
    op.add_column('game_summaries', sa.Column('accuracy_black', sa.Float(), nullable=True))
    op.add_column('game_summaries', sa.Column('opening_eco', sa.String(length=5), nullable=True))
    op.add_column('game_summaries', sa.Column('opening_name', sa.String(length=120), nullable=True))
    op.add_column('game_summaries', sa.Column('phase_acpl', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('game_summaries', sa.Column('motif_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('move_analyses', sa.Column('win_percent_before', sa.Float(), nullable=True))
    op.add_column('move_analyses', sa.Column('win_percent_after', sa.Float(), nullable=True))
    op.add_column('move_analyses', sa.Column('accuracy_percent', sa.Float(), nullable=True))
    op.add_column('move_analyses', sa.Column('is_critical_moment', sa.Boolean(), nullable=True))
    op.add_column('move_analyses', sa.Column('maia_top1_san', sa.String(length=10), nullable=True))
    op.add_column('move_analyses', sa.Column('maia_top1_prob', sa.Float(), nullable=True))
    op.add_column('move_analyses', sa.Column('maia_match_played', sa.Boolean(), nullable=True))
    op.add_column('move_analyses', sa.Column('maia_rating_used', sa.Integer(), nullable=True))
    op.add_column('move_analyses', sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('move_analyses', 'details_json')
    op.drop_column('move_analyses', 'maia_rating_used')
    op.drop_column('move_analyses', 'maia_match_played')
    op.drop_column('move_analyses', 'maia_top1_prob')
    op.drop_column('move_analyses', 'maia_top1_san')
    op.drop_column('move_analyses', 'is_critical_moment')
    op.drop_column('move_analyses', 'accuracy_percent')
    op.drop_column('move_analyses', 'win_percent_after')
    op.drop_column('move_analyses', 'win_percent_before')
    op.drop_column('game_summaries', 'motif_counts')
    op.drop_column('game_summaries', 'phase_acpl')
    op.drop_column('game_summaries', 'opening_name')
    op.drop_column('game_summaries', 'opening_eco')
    op.drop_column('game_summaries', 'accuracy_black')
    op.drop_column('game_summaries', 'accuracy_white')
    # ### end Alembic commands ###
