"""progressive_stages

Revision ID: 395888d0b107
Revises: 160707205ff6
Create Date: 2026-04-15 08:16:08.082552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '395888d0b107'
down_revision: Union[str, Sequence[str], None] = '160707205ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('games', sa.Column('analysis_stage', sa.String(length=10), nullable=True))
    op.add_column('move_analyses', sa.Column('completed_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # Backfill: existing fully-analysed rows (have both eval_before and best_move_san)
    # are considered complete across all stages so the progressive pipeline doesn't
    # re-analyse them from scratch.
    op.execute(
        """
        UPDATE move_analyses
        SET completed_stages = '["shallow","standard","deep","enrich"]'::jsonb
        WHERE eval_before IS NOT NULL AND best_move_san IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE games SET analysis_stage = 'deep'
        WHERE analysis_status = 'done'
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('move_analyses', 'completed_stages')
    op.drop_column('games', 'analysis_stage')
    # ### end Alembic commands ###
