"""add fen and comment to move_analyses

Revision ID: 62da53931d77
Revises: 357d17c50335
Create Date: 2026-04-14 14:07:44.674558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62da53931d77'
down_revision: Union[str, Sequence[str], None] = '357d17c50335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('move_analyses', sa.Column('fen', sa.String(length=100), nullable=True))
    op.add_column('move_analyses', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('move_analyses', 'comment')
    op.drop_column('move_analyses', 'fen')
    # ### end Alembic commands ###
