"""initial schema

Revision ID: 9793b233d94c
Revises: 
Create Date: 2026-04-13 21:39:21.471137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9793b233d94c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coaching_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('related_games', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coaching_insights_user_type', 'coaching_insights', ['user_id', 'type'], unique=False)
    op.create_table('connected_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_username', sa.String(length=100), nullable=False),
    sa.Column('oauth_token_enc', sa.LargeBinary(), nullable=True),
    sa.Column('auto_sync', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_game_id', sa.String(length=100), nullable=True),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.Column('white_username', sa.String(length=100), nullable=False),
    sa.Column('black_username', sa.String(length=100), nullable=False),
    sa.Column('user_color', sa.String(length=5), nullable=False),
    sa.Column('result', sa.String(length=4), nullable=False),
    sa.Column('opening_name', sa.String(length=200), nullable=True),
    sa.Column('opening_eco', sa.String(length=10), nullable=True),
    sa.Column('time_control', sa.String(length=20), nullable=True),
    sa.Column('user_elo', sa.Integer(), nullable=True),
    sa.Column('opponent_elo', sa.Integer(), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('move_count', sa.Integer(), nullable=False),
    sa.Column('import_source', sa.String(length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('ix_games_user_played', 'games', ['user_id', 'played_at'], unique=False)
    op.create_table('game_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('blunders', sa.Integer(), nullable=False),
    sa.Column('mistakes', sa.Integer(), nullable=False),
    sa.Column('inaccuracies', sa.Integer(), nullable=False),
    sa.Column('avg_eval_loss', sa.Float(), nullable=False),
    sa.Column('phase_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_trouble', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('move_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=5), nullable=False),
    sa.Column('move_san', sa.String(length=10), nullable=False),
    sa.Column('eval_before', sa.Float(), nullable=False),
    sa.Column('eval_after', sa.Float(), nullable=False),
    sa.Column('best_move_san', sa.String(length=10), nullable=False),
    sa.Column('classification', sa.String(length=15), nullable=False),
    sa.Column('time_spent_sec', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_move_analyses_game', 'move_analyses', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_move_analyses_game', table_name='move_analyses')
    op.drop_table('move_analyses')
    op.drop_table('game_summaries')
    op.drop_index('ix_games_user_played', table_name='games')
    op.drop_table('games')
    op.drop_table('connected_accounts')
    op.drop_index('ix_coaching_insights_user_type', table_name='coaching_insights')
    op.drop_table('coaching_insights')
    op.drop_table('users')
    # ### end Alembic commands ###
